apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "authz-bundle-distributor.shortname" . }}-config-loader
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        {{- include "authz-bundle-distributor.standardLabels" . | nindent 8 }}
        app: config-loader
    spec:
      serviceAccountName: {{ template "authz-bundle-distributor.fullname" . }}
      containers:
      - name: {{ template "authz-bundle-distributor.shortname" . }}-config-loader
        image: 817276302724.dkr.ecr.eu-west-1.amazonaws.com/infra/k8s-config-loader:latest_master
        imagePullPolicy: Always
        volumeMounts:
        - name: params-volume
          mountPath: /etc/params/
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ required "Undefined configloader.aws_access_key_id" .Values.configloader.aws_access_key_id }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "authz-bundle-distributor.fullname" . }}-preload
              key: AWS_SECRET_ACCESS_KEY
        - name: LABELS
          value: |
            {{- include "authz-bundle-distributor.standardLabels" . | nindent 12 }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: PREFIX
          value: {{ .Values.configloader.prefix | quote }}
        - name: RELEASE_REVISION
          value: {{ .Release.Revision | quote }}
        - name: SECRET_RESOURCE_NAME
          value: {{ template "authz-bundle-distributor.fullname" . }}
      volumes:
        - name: params-volume
          configMap:
            name: {{ template "authz-bundle-distributor.fullname" . }}-params
            items:
            - key: params.yaml
              path: params.yaml
      restartPolicy: OnFailure
  backoffLimit: 4
