---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-read-all
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
    resources: ['*.*', '*']
    apiGroups: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-creator
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - create
    resources:
      - configmaps
      - secrets
    apiGroups: ['']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4}}
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-manager
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - update
      - patch
    apiGroups: ['']
    resources:
      - configmaps
      - secrets
    resourceNames:
      - {{ template "authz-bundle-distributor.fullname" . }}-preload
      {{- range untilStep .Release.Revision 0 -1 }}
      - {{ template  "authz-bundle-distributor.fullname" $ }}-{{ . }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - delete
      - update
    apiGroups: ['', 'batch']
    resources:
      - configmaps
      - jobs
      - secrets
    resourceNames:
      - {{ template "authz-bundle-distributor.shortname" . }}-config-loader
      - {{ template "authz-bundle-distributor.fullname" . }}-preload
      - {{ template "authz-bundle-distributor.shortname" . }}-postgres-loader
      - {{ template "authz-bundle-distributor.shortname" . }}-resource-cleanup
      {{- range untilStep .Release.Revision 0 -1 }}
      - {{ template "authz-bundle-distributor.fullname" $ }}-{{ . }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" .}}-pod-cleaner
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - update
      - delete
    apiGroups: ['']
    resources: ['pods']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-12"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-read-all
subjects:
  - kind: ServiceAccount
    name: {{ template "authz-bundle-distributor.fullname" . }}
    apiGroup: ''
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: {{ template "authz-bundle-distributor.fullname" . }}-read-all
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-12"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-creator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "authz-bundle-distributor.fullname" . }}
    apiGroup: ''
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-creator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-12"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-manager
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "authz-bundle-distributor.fullname" . }}
    apiGroup: ''
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: {{ template "authz-bundle-distributor.fullname" . }}-config-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-12"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "authz-bundle-distributor.fullname" . }}
    apiGroup: ''
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: {{ template "authz-bundle-distributor.fullname" . }}-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-12"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  name: {{ template "authz-bundle-distributor.fullname" . }}-pod-cleaner
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "authz-bundle-distributor.fullname" . }}
    apiGroup: ''
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: {{ template "authz-bundle-distributor.fullname" . }}-pod-cleaner
