---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "authz-bundle-distributor.shortname" . }}-resource-cleanup
  labels:
    {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        {{- include "authz-bundle-distributor.standardLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "authz-bundle-distributor.shortname" . }}-resource-cleanup
        image: 817276302724.dkr.ecr.eu-west-1.amazonaws.com/infra/k8s-kubectl:v1.10.3
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - kubectl delete job -n {{ .Release.Namespace }} -l release={{ .Release.Name }}; \
            kubectl delete configmap -n {{ .Release.Namespace }} -l release={{ .Release.Name }}; \
            kubectl delete statefulset -n {{ .Release.Namespace }} -l release={{ .Release.Name }}; \
            kubectl delete secret -n {{.Release.Namespace}} -l release={{ .Release.Name }}
      serviceAccountName: {{ template "authz-bundle-distributor.fullname" . }}
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "authz-bundle-distributor.shortname" . }}-svc-account-cleanup
  labels:
        {{- include "authz-bundle-distributor.standardLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
          {{- include "authz-bundle-distributor.standardLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "authz-bundle-distributor.shortname" . }}-resource-cleanup
          image: 817276302724.dkr.ecr.eu-west-1.amazonaws.com/infra/k8s-kubectl:v1.10.3
          imagePullPolicy: Always
          env:
            - name: RESOURCES
              value: >
                serviceaccount/{{ template "authz-bundle-distributor.fullname" . }}
                role/{{ template "authz-bundle-distributor.fullname" . }}-read-all
                role/{{ template "authz-bundle-distributor.fullname" . }}-config-creator
                role/{{ template "authz-bundle-distributor.fullname" . }}-config-manager
                role/{{ template "authz-bundle-distributor.fullname" . }}-cleaner
                rolebinding/{{ template "authz-bundle-distributor.fullname" . }}-read-all
                rolebinding/{{ template "authz-bundle-distributor.fullname" . }}-config-creator
                rolebinding/{{ template "authz-bundle-distributor.fullname" . }}-config-manager
                rolebinding/{{ template "authz-bundle-distributor.fullname" . }}-cleaner
          command:
            - sh
            - -c
            - kubectl delete -n {{ .Release.Namespace }} $RESOURCES ;
      serviceAccountName: service-account-manager
      restartPolicy: Never
  backoffLimit: 4
